
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 28 08:23:31 COT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 7;
  public static final int LETRA = 5;
  public static final int CONVERTIR = 2;
  public static final int error = 1;
  public static final int SUMA = 3;
  public static final int ASIGNAR = 4;
  public static final int ESPACIO = 6;
  public static final int EOF = 0;
}

