
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 19:37:31 COT 2015
//----------------------------------------------------

package proyectojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONVERTIR = 4;
  public static final int error = 1;
  public static final int ALFA = 2;
  public static final int SUMA = 3;
  public static final int EOF = 0;
}

